name: Publish CLI to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci
        working-directory: packages/cli

      - name: Install semantic-release and plugins
        run: npm install --no-save semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github @semantic-release/git conventional-changelog-cli
        working-directory: packages/cli

      - name: Install conventional-changelog and preset
        run: npm install -g conventional-changelog conventional-changelog-angular

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: packages/cli

      - name: Create packages/cli/CHANGELOG.md
        run: |
          npx conventional-changelog -p angular -i packages/cli/CHANGELOG.md -s

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [ -f packages/cli/CHANGELOG.md ]; then
            git add packages/cli/CHANGELOG.md
            git commit -m "chore(changelog): update [skip ci]" || echo "No changes to commit"
            git push origin HEAD:rayan-dev
          else
            echo "No CHANGELOG.md to commit"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): manual version bump [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: packages/cli
